# frozen_string_literal: true

gem "rails"
source "https://rubygems.org"
gem "aitch", ">0"
gem "minitest"

group :development do
end

group :test do
  gem "pry-meta"
end

platforms :ruby do
  gem "rake"
end
